# Generated by Django 2.1.5 on 2019-01-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
