# Generated by Django 2.1.5 on 2019-01-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_auto_20190127_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
